### ISSUE TITLE
[feature] Resty Metrics for HTTP vs TCP Failures

### ISSUE THREAD

**Issue by onelapahead** [hyperledger/firefly-common#142]
With this library providing a metrics manager for Prometheus, and autoconfiguration for Resty clients, we should support automatically wiring up metrics from Resty clients into Prometheus.

Setting it up is a bit tricky, as the Resty client metrics must be registered only once per Prometheus registry, which the manager should handle. Clients should all refer to same global Resty client metrics / subsystem. When creating a Resty client it should be optional (possibly a separate `New` func) to provide a metrics manager and registry that it then wires itself into the client, and ensures that the metrics it depends on are registered or will be registered.

We can then use Resty's `OnError` (https://github.com/go-resty/resty?tab=readme-ov-file#onerror-hooks) to receive a hook when errors occur, determine if the error is a response error or otherwise assume it was a network error, and increment an `http_failure` vs `network_failure` counter depending. These metrics do not need specific URLs yet as that would be high cardinality.

If we wish to distinguish network errors with specific known errors and tags we could do something like: https://stackoverflow.com/questions/67646842/how-to-handle-net-errors-in-golang-properly

Once this metrics framework and basic failure counters are in place, we can consider expanding support for response time histograms, counters for particular HTTP methods and response codes, etc. leveraging `OnBeforeRequest` and `OnAfterResponse` more.

**Comment by alexwood** [comment]
Merging the above proposals I am interpretting the proposal as ...

1. enhance ffresty to have a (global) EnableClientMetrics func which configures metrics manager and registry globally for use in FFResty clients.
2. enhance ffresty to support global hooks for onError. 
3. enhance ffresty to add specific global hooks for metrics if they are configured via (1) using the global onError hooks and possibly other global hooks (2)

**Comment by onelapahead** [comment]
That proposal sounds great to me @alexwood thanks! Can iterate through the details once a draft PR is ready and we have a working example of the failure metrics as prove point for hooks / metrics wiring framework 🙇🏻

**Comment by alexwood** [comment]
Changes merged that add http response metrics and also non http error metrics

@onelapahead can we close this issue or do you wish to keep it open for some additional follow on requirements we want to include.

**Comment by EnriqueL8** [comment]
I think we can close this one! Thanks for the contribution @alexwood and @onelapahead
